openapi: 3.0.0
info:
  version: 0.0.
  title: Persona; Finance API
  description: A simple API for a personal finance summary
paths:
  /financeResource:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response

  /financialStats:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
      responses:
        '200':
          description: "Financial stats calculated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    type: string